. Dockerfile.in, Dockerfile.arm.in: fixed a bug 'source ${HOME}/.bashrc' cannot be run in non-interactive mode, and caused nvm unaccessable because the environment variables depending on .bashrc failed to set. we have now changed to source nvm.sh directly to setup the environment variables.

diff --git a/tools/Dockerfile.in b/tools/Dockerfile.in
--- a/tools/Dockerfile.in
+++ b/tools/Dockerfile.in
@@ -1,43 +1,52 @@
 FROM ubuntu:latest
 MAINTAINER woodhead99@gmail.com
 RUN apt-get update
-RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
+RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata locales apt-utils
 SHELL ["/bin/bash", "-c"]
+
+RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
+ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
 
 #install the kerberos servers and client
 ADD ./initkrb5.sh /root
-RUN apt-get install -qq krb5-kdc krb5-admin-server krb5-user 
+RUN apt-get install -qq krb5-kdc krb5-admin-server krb5-user
 #setup the kdc and kadmind and start the servers
 CMD bash /root/initkrb5.sh || exit 1
 #login with principal zhiming
 CMD kinit -k -t /etc/krb5.keytab zhiming || exit 2
 
 RUN apt-get install -y --fix-missing gcc g++ python3 python3-dev python3-pip python3-build flex bison \
-libtool shtool automake autoconf autotools-dev make dbus dbus-bin libdbus-1-3 \
-libdbus-1-dev libjsoncpp-dev libkrb5-3 libkrb5-dev liblz4-1 \
-liblz4-dev lz4 openssl libssl3 libssl-dev libcppunit-1.15-0 libcppunit-dev \
-libfuse3-3 libfuse3-dev fuse3 bash net-tools procps swig cmake attr \
+libtool shtool automake autoconf autotools-dev make dbus dbus-bin \
+libdbus-1-dev libjsoncpp-dev libkrb5-dev \
+liblz4-dev lz4 openssl libssl-dev libcppunit-dev \
+libfuse3-dev fuse3 bash net-tools procps swig cmake attr \
 libcommons-cli-java curl figlet python3-urwid gettext
 RUN apt-get install -y openjdk-8-jdk-headless || apt-get install -y \
     openjdk-11-jdk-headless || apt-get install -y openjdk-17-jdk-headless 
-# ubuntu 22.04's version of nodejs is outdated, lets install node 20 from nodejs'
-# site instead.
 
-RUN for i in $(seq 1 100);do if curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
- && . ${HOME}/.bashrc && nvm install 20 && node -v && nvm list; then break;fi;done
-RUN  if ! ( . ${HOME}/.bashrc && nvm list ); then echo -e "\e[33mcannot download nvm and nodejs..., disable JS support\e[0m"; touch ${HOME}/nojs; fi
+
+# ubuntu 22.04's official version of nodejs is outdated, lets install node 20 from nodejs'
+# site instead.
+ENV NVM_DIR="${HOME}/.nvm"
+
+RUN success="false";for i in $(seq 1 100);do \
+    if ! curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash; then continue; fi; \
+    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; \ 
+    if nvm install 20 && node -v && nvm list; then success="true";break;fi;\
+    done; \
+    if [[ "$success" == "false" ]]; then echo -e "\e[33mcannot download nvm and nodejs..., disable JS support\e[0m"; touch ${HOME}/nojs; fi
 
 RUN apt-get -y install sip-tools python3-sipbuild || apt-get -y install sip-dev python3-sip python3-sip-dev || true
-RUN apt-get -y install libjsoncpp1 || apt-get -y install libjsoncpp25 || apt-get -y install libjsoncpp24
 RUN apt-get -y install git devscripts debhelper expect vim screen tmux iputils-ping;
 RUN cd ${HOME};for i in $(seq 1 100);do if git clone 'https://github.com/zhiming99/GmSSL.git'; then break; fi;done
 RUN cd ${HOME};cd ./GmSSL;mkdir build;cd build;cmake ..;make;make install
 RUN apt-get -y install python3-wheel python3-numpy || pip3 install wheel numpy
-RUN if [ ! -f ${HOME}/nojs ]; then . ${HOME}/.bashrc && npm -g install @JS_NODE_PACKAGES@;fi
+RUN if [ ! -f ${HOME}/nojs ]; then . ${NVM_DIR}/nvm.sh; npm -g install @JS_NODE_PACKAGES@;fi
 RUN cd ${HOME};for i in $(seq 1 100);do if git clone 'https://github.com/zhiming99/rpc-frmwrk.git';then break;fi;done
 RUN cd ${HOME}/rpc-frmwrk && libtoolize && aclocal && autoreconf -vfi && \
 automake --add-missing && autoconf; echo `pwd`;ls -l `pwd`
-RUN if [ -f ${HOME}/nojs ]; then opt='--disable-js'; fi;. ${HOME}/.bashrc && cd ${HOME}/rpc-frmwrk && bash cfgsel -r $opt && make -j4 && make install; echo 'export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/rpcf' >> ${HOME}/.bashrc
+RUN if [ -f ${HOME}/nojs ]; then opt='--disable-js'; else . ${NVM_DIR}/nvm.sh; fi; cd ${HOME}/rpc-frmwrk && bash cfgsel -r $opt && make -j4 && make install; \
+    echo 'export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/rpcf' >> ${HOME}/.bashrc
 ADD ./testcfgs/mincfg.json /root
 RUN python3 /usr/local/bin/rpcf/rpcfgnui.py ${HOME}/mincfg.json
 RUN if [ -f ${HOME}/nojs ]; then echo -e "\e[33mrpc-frmwrk is built without JS support \e[0m"; rm -f ${HOME}/nojs; else cd ${HOME}/rpc-frmwrk; figlet -cm 60 'RPC-FRMWRK ROCKS !';fi
